config/routes.rb
Mau::Application.routes.draw do
  resources :articles
  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
   attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

    def show
      @article = Article.find(params[:id])
    end

	def new
      @article = Article.new
	end

    def create
      @article = Article.new(params[:article])
      @article.save
      redirect_to article_path(@article)
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to action:  'index'	
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
     @article = Article.find(params[:id])
     @article.update_attributes(params[:article])
     redirect_to article_path(@article)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit an Article</h2>

<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1> All Articles<h1>
	<ul id ="articles">
		<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article),  class: 'article_title' %>
		</li>
		<% end %>
	</ul>
	<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h2> New blog here <h2>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2></br>
<p><%= @article.body %><p>

<%= link_to "Back to Articles List", articles_path %></hr>
<%= link_to "Delete", article_path(@article), method: :delete , confirm:  "Do yow want to delete it"  %></hr>
<%= link_to "edit", edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mau</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>